In [17]:
import sys 

sys.path.append("/Users/ngokykhanhthu/Documents/Mental_Health_n_LLMs/")

In [18]:
import re 
# import requests
from bs4 import BeautifulSoup
import pandas as pd 
import numpy as np 
import os
import json
import subprocess
from datetime import datetime
from mental.config import RAW_DIR, INTERIM_DIR, PROCESSED_DIR, FINAL_DIR, FINAL_DIR_2, DATASET, DATA_KEYWORD, CHAT_GPT_QUESTION

os forces python to interract with the operating system 
sys interracts with python interpreter itself

In [19]:
def is_unix_time(object): 
    '''
    Checks to see if a given string is unix time or not 
    
    Args: 
        object that needs to be checked 
    
    Returns: 
        Boolean value, true when it is unix time stamp, false if else 
    '''
    unix_time = re.match(r'^\d{10}\.\d+?$', str(object))
    
    if unix_time: 
        return True 
    return False

In [20]:
is_unix_time(1548319538)

False

cus some strings of random numbs have timestamps as well but they dont have info abt nanoseconds like messages do

In [21]:
# test that  
is_unix_time(1760895234.572819)

True

In [22]:
# TODO current results are converted to EST time zone, should change to reflect the users timezone instead
# output is currently not timezone aware 
# shifts for daylight saving time as well 

def convert_unix_time(unix_stamp): 
    """
    Given unix timestamp, convert it to date time object 

    Args:
        unix_stamp (str): time stamp 

    Returns:
        datetime: datetime object in YYYY/MM/DD HH:MM:SS
    """
    return datetime.fromtimestamp(unix_stamp)

In [23]:
# test that  
convert_unix_time(1465073678)

datetime.datetime(2016, 6, 4, 16, 54, 38)

In [24]:
convert_unix_time(1760895234.572819)

datetime.datetime(2025, 10, 19, 13, 33, 54, 572819)

In [25]:
# probs drop 

# def check_if_chat_message(unix_stamp, data): 
#     """
#     helper method for create_csv_files
#     given unix stamp and the json list, figure out if it is gibberish or chat message
   
#     Args:
#         unix_stamp (float): an unix timestamp 
#         data (list): the json file 

#     Returns: 
#         True if it is a valid chat message
#         False otherwise  
#     """
#     # TODO 
#     return True

In [26]:
def extract_msg(unix_stamp, data): 
    """
    helper method for create_csv_files
    given unix stamp and the json list, extract chat message
    Args:
        unix_stamp (float): an unix timestamp 
        data (list): the json file 

    Returns: 
        str: message
    """
    # curr_index = data.index(unix_stamp) + 1
    strings = []
    
    entered_string = False 
    while curr_index < len(data):
        curr_element = data[curr_index]
        if isinstance(curr_element, str):
            strings.append(curr_element)  
            curr_index += 1
        elif not strings: 
            curr_index += 1 
        else: 
            curr_index = len(data)

    return repr(str(strings[-1]))

In [27]:
# probs drop 
# def classify_sender(message): 
#     """
#     helper method for create_csv_files
#     given unix stamp and the json list, figure out who sent message 
#      Args:
#         message (str): a message extracted 

#     Returns: 
#         str: chatgpt/user 
#     """
#     msg_raw = repr(message)
#     if msg_raw[0] == "\\'": 
#         return "chatgpt" 
#     return "user"
#     # return bool(re.match(r'.*("\""|"\'").*', message[0]))
#     # message_raw = repr(message)[1:]
#     # state =  bool(re.fullmatch(r'.*[\']".*', message_raw))
#     # if state: 
#     #     return "chatgpt"
#     # return "user"

In [28]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.keys()
print(list(x) + [])

['brand', 'model', 'year']

In [29]:
def check_msg(keys, data, i): 
    if isinstance(data[i+1], dict) and list(data[i+1].keys) == keys and isinstance(data[i+2], list) and len(data[i+2]) == 1 and isinstance(data[i+3], str): 
         
        return data[i+3]

In [48]:
len("")

0

In [51]:
def create_csv_files(file_path, order_of_file): 
    """
    given json list file path, extracts chat info and outputs csv file
    
    Args:
        file_path (os.path): path to json file   
    """

    # load json file 
    with open(file_path, "r", encoding='utf-8', errors='strict') as f:
        # type(data) = dict
        data = json.load(f)

    # initialise df 
    rows = []
    
    # meta data stuff 
    title = ""
    create_time = 0 
    update_time = 0
    authors_codes = []
    # go through the json list 
    for i in range(0,len(data)-1, 1): 
        sender = ""
        # extract title 
        # isinstance(data[i], str) and 
        if data[i] == "title" and len(title) == 0: 
            title = data[i+1]
            continue
    
        if data[i] == "content" and isinstance(data[i+1], dict): 
            keys = list(data[i+1].keys()) 
            authors_codes += keys
            continue
        
        if not is_unix_time(data[i]): 
            continue 

        timestamp = data[i]

        # extract file create time 
        if create_time == 0 : 
            create_time = convert_unix_time(timestamp)
            continue 
            
        # extract file latest update time 
        elif update_time == 0:     
            update_time = convert_unix_time(timestamp)
            continue 
    
        
        # extract timestamp + message 
        if not (
            isinstance(data[i+1], dict)
            and list(data[i+1].keys()) == authors_codes
            and isinstance(data[i+2], list)
            # and len(data[i+2]) == 1
            and isinstance(data[i+3], str)
        ):
            # message = data[i+3]
            # print(timestamp)
            # i += 3

            # if not message:
            continue  
        
        message = data[i+3]
        print(timestamp)
        i += 3
        # if there is a timestamp right afterwards, probs a chatgpt response 
        # elif i + 1 < len(data) and is_unix_time(data[i+1]): 
        #     print("data at ", i, "is ", data[i], "anddd second cond state is ", is_unix_time(data[i+1]))

        #     timestamp =  data[i+1]
        #     sender = "chatgpt"
            
        # # deal w the extra timestamp
        # elif  i - 1  > 0 and is_unix_time(data[i-1]) : 
        #     continue

        # # if there is not, check if gibberish. 
        # elif not check_if_chat_message(timestamp, data): 
        #     continue

        # if not, get the message 
        # message = extract_msg(timestamp, data[i+1:]) 

        # if 'sender' != "": 
        #     sender = classify_sender(message)

        # update rows 
        rows.append([title, 
                        create_time, 
                        update_time,
                        "pending", 
                        # convert_unix_time(timestamp), 
                        timestamp, 
                        message])
    
    df = pd.DataFrame(rows, columns=['title', 'create_time', "update_time", 'sender', 'timestamp', 'message'])
    df.to_csv(f"../data/3.final_v3/{int(order_of_file)}_extracted_chat.csv", index=False)

In [46]:
for file in os.listdir(f"../{PROCESSED_DIR}"):
    print(file)

3_json_output.json
8_json_output.json
7_json_output.json
2_json_output.json
6_json_output.json
1_json_output.json
5_json_output.json
0_json_output.json
4_json_output.json

In [52]:
for file in os.listdir(f"../{PROCESSED_DIR}"):
        order_of_file = file[0] 
        file_path = os.path.join(f"../{PROCESSED_DIR}", file)
        create_csv_files(file_path, order_of_file)

1757974691.816
1757974692.100187
1757974777.825
1757974778.11673
1757975037.875
1757975038.44421
1757975118.397
1757975118.701429
1757975519.761
1757975520.150038
1757975572.049
1757975572.595284
1757975776.86
1757975777.403628
1757975819.638
1757975819.996392
1757975922.212
1757975922.566548
1757976083.953
1757976084.67017
1757976181.826
1757976182.253866
1757976242.22
1757976242.559552
1757976588.443
1757976588.846038
1757976721.646
1757976722.097727
1757976986.643
1757976987.056702
1757977254.298
1757977254.738421
1757977616.693
1757977617.100507
1757977760.788
1757977761.227761
1757977811.702
1757977812.134515
1757977910.59
1757977911.152513
1757978038.17
1757978038.695079
1757978098.86
1757978100.077668
1757978190.38
1757978190.807299
1757978400.067
1757978400.669567
1757978625.901
1757978626.358658
1757978819.519
1757978820.020785
1761187999.349
1761188006.129878
1761188029.600937
1761188132.21
1761188137.857181
1761188142.573
1761188145.73925
1761187459.691
1761187462.862657
1761187471.988
1761187481.4586291
1761187518.15547
1761187519.998
1761187605.570825
1752521093.705
1752521095.201225
1752521587.931
1752521588.475199
1752522393.03
1752522393.640236
1752522613.089
1752522613.749871
1752522863.581
1752522864.045229
1752523038.498
1752523039.333583
1752525267.326
1752525267.977018
1753809594.532
1753809595.202004
1753811314.994
1753811315.504511
1753811567.827
1753811568.182347
1753812575.088
1753812575.492411
1753895847.598
1753895847.949069
1753896054.666
1753896055.218893
1753896159.378
1753896159.704192
1753896423.483
1753896423.838534
1753899214.421
1753899214.835814
1753899813.802
1753899814.357239
1753899981.753
1753899982.19216
1753903501.798
1753903502.152815
1754325035.462
1754325037.397833
1754325066.174
1754325066.645049
1754325155.957
1754325156.311154
1754325646.515
1754325647.28981
1754591808.094
1754591808.703172
1754591960.288
1754591960.633034
1754592274.338833
1754592353.999
1754592354.366367
1754592412.777
1754592413.650094
1754592577.347
1754592577.817775
1754595001.505
1754595002.000795
1754595431.756
1754595432.37613
1754595585.91
1754595586.496075
1754595705.262
1754595705.776032
1754595821.348
1754595821.83765
1756824925.467
1756824926.1091073
1756824926.104007
1756837623.777
1756837624.331763
1756837765.446
1756837766.175682
1756838234.014
1756838235.532516
1758120014.319
1758120015.87973
1758123792.246
1758123792.834332
1755790635.704
1755790636.316681
1755790836.58
1755790837.275532
1755790937.339
1755790938.362413
1755791244.381
1755791245.428114
1755791297.634
1755791298.453949
1755791318.429
1755791319.402347
1755791371.254
1755791371.883222
1755791520.068
1755791521.419095
1755791856.357
1755791857.553306
1755792291.001
1755792291.733503
1755792376.079
1755792380.860246
1755792415.264
1755792416.002157
1755792462.104
1755792463.430868
1759891252.668
1759891369.836065
1759891375.683522
1759891526.866
1759891618.296839
1759405137.026
1759405138.678362
1759405139.966264
1759405650.591
1759405651.031469
1759409355.193
1759409355.913158
1759409871.301
1759409871.706642
1760635203.828
1760635279.258958
1760635284.601403
1760635350.673
1760635359.124653
1760635372.585853
1760635536.401
1760635552.756593
1760635553.903
1760635564.482273
1760635566.09
1760635572.973454
1760636248.752
1760636257.079
1760636262.538033
1760637084.145059

In [36]:
import os
print(os.getcwd())

/Users/ngokykhanhthu/Documents/Mental_Health_n_LLMs/notebooks

In [ ]:
create_csv_files(f"../{PROCESSED_DIR}/8_json_output.json")

1761187999.349
1761188006.129878
1761188029.600937
1761188132.21
1761188137.857181
1761188142.573
1761188145.73925

In [ ]:
df = pd.read_csv(f"../{DATASET}")

In [ ]:
df.head(2)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,neurotype_validated_3,neurotype_validated_4,neurotype_validated_5,neurotype_validated_6,dem_gender,dem_gender_3_TEXT,dem_institution,dem_institution_7_TEXT,Logistics_1,Logistics_2
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,"Please answer the questions below, rating your...","Please answer the questions below, rating your...","Please answer the questions below, rating your...","Please answer the questions below, rating your...",What is your gender? - Selected Choice,What is your gender? - Other - Text,From what institution are you from? - Selected...,From what institution are you from? - Other - ...,Do you want to stay in contact for future rese...,Do you want to be entered into the raffle to w...
1,"{""ImportId"":""startDate"",""timeZone"":""America/Ne...","{""ImportId"":""endDate"",""timeZone"":""America/New_...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID15_3""}","{""ImportId"":""QID15_4""}","{""ImportId"":""QID15_5""}","{""ImportId"":""QID15_6""}","{""ImportId"":""QID7""}","{""ImportId"":""QID7_3_TEXT""}","{""ImportId"":""QID103""}","{""ImportId"":""QID103_7_TEXT""}","{""ImportId"":""QID47""}","{""ImportId"":""QID48""}"

In [ ]:
list = [col for col in df.columns.to_list() if "LLM" in col]

In [ ]:
print(list)

['1_LLM_S_7_2_Id', '1_LLM_S_7_2_Name', '1_LLM_S_7_2_Size', '1_LLM_S_7_2_Type', '2_LLM_S_7_2_Id', '2_LLM_S_7_2_Name', '2_LLM_S_7_2_Size', '2_LLM_S_7_2_Type', '3_LLM_S_7_2_Id', '3_LLM_S_7_2_Name', '3_LLM_S_7_2_Size', '3_LLM_S_7_2_Type', '4_LLM_S_7_2_Id', '4_LLM_S_7_2_Name', '4_LLM_S_7_2_Size', '4_LLM_S_7_2_Type', '5_LLM_S_7_2_Id', '5_LLM_S_7_2_Name', '5_LLM_S_7_2_Size', '5_LLM_S_7_2_Type']

In [ ]:
df.loc[0:10, list]

,1_LLM_S_7_2_Id,1_LLM_S_7_2_Name,1_LLM_S_7_2_Size,1_LLM_S_7_2_Type,2_LLM_S_7_2_Id,2_LLM_S_7_2_Name,2_LLM_S_7_2_Size,2_LLM_S_7_2_Type,3_LLM_S_7_2_Id,3_LLM_S_7_2_Name,3_LLM_S_7_2_Size,3_LLM_S_7_2_Type,4_LLM_S_7_2_Id,4_LLM_S_7_2_Name,4_LLM_S_7_2_Size,4_LLM_S_7_2_Type,5_LLM_S_7_2_Id,5_LLM_S_7_2_Name,5_LLM_S_7_2_Size,5_LLM_S_7_2_Type
0,"Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se...","Or if you prefer, upload a file to the chat se..."
1,"{""ImportId"":""1_QID63_FILE_ID""}","{""ImportId"":""1_QID63_FILE_NAME""}","{""ImportId"":""1_QID63_FILE_SIZE""}","{""ImportId"":""1_QID63_FILE_TYPE""}","{""ImportId"":""2_QID63_FILE_ID""}","{""ImportId"":""2_QID63_FILE_NAME""}","{""ImportId"":""2_QID63_FILE_SIZE""}","{""ImportId"":""2_QID63_FILE_TYPE""}","{""ImportId"":""3_QID63_FILE_ID""}","{""ImportId"":""3_QID63_FILE_NAME""}","{""ImportId"":""3_QID63_FILE_SIZE""}","{""ImportId"":""3_QID63_FILE_TYPE""}","{""ImportId"":""4_QID63_FILE_ID""}","{""ImportId"":""4_QID63_FILE_NAME""}","{""ImportId"":""4_QID63_FILE_SIZE""}","{""ImportId"":""4_QID63_FILE_TYPE""}","{""ImportId"":""5_QID63_FILE_ID""}","{""ImportId"":""5_QID63_FILE_NAME""}","{""ImportId"":""5_QID63_FILE_SIZE""}","{""ImportId"":""5_QID63_FILE_TYPE""}"
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from mental.chat_gpt_scraper import find_links
from mental.config import CHAT_GPT_QUESTION

In [ ]:
html_links = find_links(CHAT_GPT_QUESTION)

In [ ]:
list(html_links)

['https://chatgpt.com/share/68de6922-d988-8001-8f7c-ab05d2f633d7',
 'https://chatgpt.com/share/68e7f213-5e50-8001-8742-87be6dd95d46',
 'https://chatgpt.com/share/68e80b00-f5b0-8013-a344-6aaccceb8336',
 'https://chatgpt.com/share/68e80ec1-9684-8000-b406-249e306bd728',
 'https://chatgpt.com/share/68f13246-1b60-8001-95a2-031ec8274d6c',
 'https://chatgpt.com/share/68f1543e-8a44-8003-9877-578d28b398c4',
 'https://chatgpt.com/share/68f52102-9200-800b-8ba7-579ba8a629dd',
 'https://chatgpt.com/share/68f99741-f668-8001-a7f1-ee6ea11094d8',
 'https://chatgpt.com/share/68f9993d-7038-8001-899f-986bb3f8c630']